version: '3'

services:
  api_service:
    build:
      context: api_service
      dockerfile: Dockerfile
    ports:
    - "3000:3000"
    depends_on:
    - database
    - geth
    
  database:
    image: mongo

  geth:
    image: ethereum/client-go:stable
